"use client"

import * as React from "react"
import Link from "next/link"
import {
  ArrowLeftIcon,
  PlusIcon,
  TableIcon,
  TrashIcon,
} from "@phosphor-icons/react"

import { saveDataTableAction } from "@/lib/actions/data-table-actions"
import type { DataTable, DataTableColumn, DataTableColumnType } from "@/lib/domain/data-table"
import { createDefaultColumn } from "@/lib/domain/data-table"
import { validateSaveDataTableInput } from "@/lib/validation/data-table-schema"
import {
  RESOURCE_DESCRIPTION_MAX_LENGTH,
  RESOURCE_NAME_MAX_LENGTH,
  TABLE_COLUMN_KEY_MAX_LENGTH,
  TABLE_COLUMN_LABEL_MAX_LENGTH,
  TABLE_COLUMN_MAX_COUNT,
} from "@/lib/validation/limits"
import { Button } from "@amakai/shared/components/ui/button"
import { Input } from "@amakai/shared/components/ui/input"
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@amakai/shared/components/ui/field"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@amakai/shared/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@amakai/shared/components/ui/table"
import { Textarea } from "@amakai/shared/components/ui/textarea"

const COLUMN_TYPES: Array<{ label: string; value: DataTableColumnType }> = [
  { label: "Text", value: "string" },
  { label: "Number", value: "number" },
  { label: "Boolean", value: "boolean" },
  { label: "JSON", value: "json" },
]

export interface TableSchemaViewProps {
  table: DataTable
}

function slugifyKey(label: string, index: number) {
  const base = label
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
  return base || `field_${index}`
}

function isAutoGeneratedKey(key: string) {
  return /^field_\d+$/.test(key)
}

export function TableSchemaView({ table }: TableSchemaViewProps) {
  const [name, setName] = React.useState(table.name)
  const [description, setDescription] = React.useState(table.description ?? "")
  const [columns, setColumns] = React.useState<DataTableColumn[]>(table.columns)
  const [isSaving, setIsSaving] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)
  const [savedMessage, setSavedMessage] = React.useState<string | null>(null)
  const loadedTableIdRef = React.useRef(table.id)

  React.useEffect(() => {
    if (loadedTableIdRef.current === table.id) {
      return
    }

    loadedTableIdRef.current = table.id
    setName(table.name)
    setDescription(table.description ?? "")
    setColumns(table.columns)
  }, [table.id, table.name, table.description, table.columns])

  const normalizeColumns = (nextColumns: DataTableColumn[]) => {
    return nextColumns.map((column, index) => ({
      ...column,
      key: column.key.trim() || slugifyKey(column.label, index + 1),
      label: column.label.trim() || `Field ${index + 1}`,
    }))
  }

  const handleSave = async () => {
    setError(null)
    setSavedMessage(null)
    setIsSaving(true)

    const normalizedColumns = normalizeColumns(columns)
    const validation = validateSaveDataTableInput({
      id: table.id,
      name,
      description,
      columns: normalizedColumns,
    })

    if (!validation.ok) {
      setIsSaving(false)
      setError(validation.error)
      return
    }

    const result = await saveDataTableAction({
      id: table.id,
      name: validation.data.name,
      description: validation.data.description ?? undefined,
      columns: validation.data.columns,
    })

    setIsSaving(false)

    if ("error" in result) {
      setError(result.error)
      return
    }

    setName(result.table.name)
    setColumns(result.table.columns)
    setSavedMessage("Saved.")
  }

  const handleAddColumn = () => {
    setColumns((current) => {
      if (current.length >= TABLE_COLUMN_MAX_COUNT) {
        setError(`Tables may have at most ${TABLE_COLUMN_MAX_COUNT} columns.`)
        return current
      }
      return [...current, createDefaultColumn(current.length + 1)]
    })
  }

  const handleRemoveColumn = (index: number) => {
    setColumns((current) =>
      current.length <= 1 ? current : current.filter((_, i) => i !== index)
    )
  }

  const handleColumnLabelBlur = (index: number) => {
    setColumns((current) =>
      current.map((entry, i) => {
        if (i !== index || !isAutoGeneratedKey(entry.key)) {
          return entry
        }
        return {
          ...entry,
          key: slugifyKey(entry.label, index + 1),
        }
      })
    )
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex min-w-0 flex-col gap-3">
          <Button
            variant="ghost"
            size="sm"
            className="w-fit px-0"
            render={<Link href="/design/tables" />}
          >
            <ArrowLeftIcon data-icon="inline-start" />
            Back to tables
          </Button>
          <div className="flex flex-col gap-2">
            <h1 className="font-heading text-2xl font-medium tracking-tight">
              {name || "Untitled table"}
            </h1>
            <p className="max-w-2xl text-sm text-muted-foreground">
              Set the table name and columns. Open the editor when you are ready
              to add rows.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <Button
            variant="outline"
            render={<Link href={`/design/tables/${table.id}/data`} />}
          >
            <TableIcon data-icon="inline-start" />
            Open editor
          </Button>
          <Button onClick={handleSave} disabled={isSaving}>
            {isSaving ? "Saving…" : "Save"}
          </Button>
        </div>
      </div>

      {error ? <p className="text-sm text-destructive">{error}</p> : null}
      {savedMessage ? (
        <p className="text-sm text-muted-foreground">{savedMessage}</p>
      ) : null}

      <FieldGroup className="gap-4 border p-4">
        <Field>
          <FieldLabel htmlFor="table-name">Name</FieldLabel>
          <Input
            id="table-name"
            value={name}
            maxLength={RESOURCE_NAME_MAX_LENGTH}
            onChange={(event) => setName(event.target.value)}
          />
          <FieldDescription>
            Table names must be unique (up to {RESOURCE_NAME_MAX_LENGTH}{" "}
            characters). Workflows reference tables by name.
          </FieldDescription>
        </Field>
        <Field>
          <FieldLabel htmlFor="table-description">Description</FieldLabel>
          <Textarea
            id="table-description"
            value={description}
            rows={2}
            maxLength={RESOURCE_DESCRIPTION_MAX_LENGTH}
            onChange={(event) => setDescription(event.target.value)}
          />
        </Field>
      </FieldGroup>

      <div className="flex flex-col gap-3">
        <div className="flex items-center justify-between gap-4">
          <h2 className="text-sm font-medium">Columns</h2>
          <Button variant="outline" size="sm" onClick={handleAddColumn}>
            <PlusIcon data-icon="inline-start" />
            Add column
          </Button>
        </div>

        <div className="border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Label</TableHead>
                <TableHead>Key</TableHead>
                <TableHead>Type</TableHead>
                <TableHead className="w-[80px] text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {columns.map((column, index) => (
                <TableRow key={`column-${index}`}>
                  <TableCell>
                    <Input
                      value={column.label}
                      maxLength={TABLE_COLUMN_LABEL_MAX_LENGTH}
                      onChange={(event) => {
                        const label = event.target.value
                        setColumns((current) =>
                          current.map((entry, i) =>
                            i === index ? { ...entry, label } : entry
                          )
                        )
                      }}
                      onBlur={() => handleColumnLabelBlur(index)}
                    />
                  </TableCell>
                  <TableCell>
                    <Input
                      value={column.key}
                      className="font-mono text-xs"
                      maxLength={TABLE_COLUMN_KEY_MAX_LENGTH}
                      onChange={(event) => {
                        const key = event.target.value
                        setColumns((current) =>
                          current.map((entry, i) =>
                            i === index ? { ...entry, key } : entry
                          )
                        )
                      }}
                    />
                  </TableCell>
                  <TableCell>
                    <Select
                      items={COLUMN_TYPES}
                      value={column.type}
                      onValueChange={(next) => {
                        if (!next) return
                        setColumns((current) =>
                          current.map((entry, i) =>
                            i === index
                              ? { ...entry, type: next as DataTableColumnType }
                              : entry
                          )
                        )
                      }}
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent alignItemWithTrigger={false} side="bottom">
                        <SelectGroup>
                          {COLUMN_TYPES.map((item) => (
                            <SelectItem key={item.value} value={item.value}>
                              {item.label}
                            </SelectItem>
                          ))}
                        </SelectGroup>
                      </SelectContent>
                    </Select>
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={columns.length <= 1}
                      onClick={() => handleRemoveColumn(index)}
                    >
                      <TrashIcon data-icon="inline-start" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}
